FROM python:3.10-slim

WORKDIR /app

# Installation des dépendances système légères
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copie et installation des dépendances locales au dossier inference
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Création du dossier structurel pour recevoir les modèles au runtime
RUN mkdir -p models

# Copie de l'application FastAPI
COPY app.py .

EXPOSE 5000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000"]