apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-svc
  labels:
    app: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring-container
        image: ton-dockerhub/monitoring:latest
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-svc
spec:
  type: ClusterIP
  selector:
    app: monitoring
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090